### ISSUE TITLE
Update Function

### ISSUE THREAD

**Issue by ElectronSz** [TutorialEdge/go-fiber-rest-api-tutorial#1]
Kindly share the update function so everyone can see if they did right

**Comment by ElectronSz** [comment]
`

     //Response structure
          type Response struct {
	            Status  int
	           Message string
           }

        //EditBook : edit one book
        func EditBook(c *fiber.Ctx) {
	        db := database.DBConn
	        book := new(Book)

	if err := c.BodyParser(book); err != nil {
		c.Status(400).SendString(err.Error())
	}

	isupdated := db.Model(book).Updates(Book{Title: book.Title, Author: book.Author, Rating: book.Rating})

	if isupdated == nil {
		res := Response{Status: 400, Message: "Error Updating book"}
		c.Status(200).JSON(res)
	}
	res := Response{Status: 200, Message: "Book Edited Successfully"}
	c.Status(200).JSON(res)

}
`

**Comment by elliotforbes** [comment]
Hey @ElectronSz - 

This looks good, though a few things need updated:

I would change the response in your:

```go
if isUpdated == nil {
	res := Response{Status: 500, Message: "Error Updating book"}
	c.Status(500).JSON(res)
}
```

You want the Status in both the response object you are serializing into JSON and the HTTP response itself to be a `500 - Internal Server Error` HTTP status code. 

A minor thing as well, I would change `isupdated` -> `isUpdated` for better readability! 

Hope this helps!

**Comment by ElectronSz** [comment]
Noted, thanks
